-- Esquema inicial del Servicio Académico.
-- Ver docs/03-modelo-datos.md para el diagrama entidad-relación y la
-- justificación de cada tabla y decisión de modelado.
--
-- Nota de portabilidad: se usa "GENERATED BY DEFAULT AS IDENTITY" (estándar
-- ANSI SQL, soportado por H2 y por PostgreSQL 10+) en vez de BIGSERIAL, para
-- que la misma migración corra igual en el H2 de esta prueba técnica y en
-- un PostgreSQL real de producción sin tener que mantener dos versiones.

CREATE TABLE estudiante (
    codigo_estudiante   VARCHAR(20)   PRIMARY KEY,
    nombre              VARCHAR(150)  NOT NULL,
    sincronizado_en     TIMESTAMP     NOT NULL
);

CREATE TABLE materia (
    codigo_materia      VARCHAR(20)   PRIMARY KEY,
    nombre              VARCHAR(150)  NOT NULL,
    creditos            SMALLINT      NOT NULL CHECK (creditos > 0)
);

CREATE TABLE periodo_academico (
    codigo              VARCHAR(10)   PRIMARY KEY,
    fecha_inicio        DATE          NOT NULL,
    fecha_fin           DATE          NOT NULL,
    vigente             BOOLEAN       NOT NULL DEFAULT FALSE
);

CREATE TABLE matricula (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_estudiante   VARCHAR(20)   NOT NULL REFERENCES estudiante(codigo_estudiante),
    codigo_materia      VARCHAR(20)   NOT NULL REFERENCES materia(codigo_materia),
    periodo_academico   VARCHAR(10)   NOT NULL REFERENCES periodo_academico(codigo),
    grupo               VARCHAR(5)    NOT NULL,
    estado              VARCHAR(20)   NOT NULL DEFAULT 'EN_CURSO'
                                       CHECK (estado IN ('EN_CURSO', 'APROBADA', 'REPROBADA', 'CANCELADA')),
    nota_actual         NUMERIC(3,2)  NULL CHECK (nota_actual >= 0.00 AND nota_actual <= 5.00),
    CONSTRAINT uq_matricula UNIQUE (codigo_estudiante, codigo_materia, periodo_academico)
);

CREATE INDEX idx_matricula_estudiante_periodo ON matricula (codigo_estudiante, periodo_academico);

CREATE TABLE evaluacion (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id        BIGINT        NOT NULL REFERENCES matricula(id),
    tipo                VARCHAR(20)   NOT NULL
                                       CHECK (tipo IN ('PARCIAL', 'QUIZ', 'TAREA', 'PROYECTO', 'EXAMEN_FINAL', 'OTRO')),
    nombre              VARCHAR(150)  NOT NULL,
    valor               NUMERIC(3,2)  NOT NULL CHECK (valor >= 0.00 AND valor <= 5.00),
    porcentaje          NUMERIC(5,2)  NOT NULL CHECK (porcentaje > 0.00 AND porcentaje <= 100.00),
    fecha               DATE          NOT NULL
);

CREATE INDEX idx_evaluacion_matricula ON evaluacion (matricula_id);
