-- Datos de prueba para poder ejercitar el servicio de punta a punta sin
-- depender del sincronizador real desde el ERP (ver docs/01-arquitectura.md).
--
-- El conjunto está pensado para una demo que muestre los tres casos
-- interesantes del contrato:
--   1. Una matrícula con evaluaciones ya cargadas y su nota_actual poblada.
--   2. Una matrícula sin ninguna evaluación (nota_actual NULL), para ver cómo
--      pasa a tener valor tras llamar al endpoint de sincronización.
--   3. Un periodo histórico, para ejercitar el parámetro ?periodo.
--
-- Nota: no se insertan valores explícitos de id en matricula ni en evaluacion
-- (son GENERATED BY DEFAULT AS IDENTITY). Las evaluaciones referencian su
-- matrícula con INSERT ... SELECT por las columnas de negocio.

INSERT INTO estudiante (codigo_estudiante, nombre, sincronizado_en) VALUES
    ('A00123456', 'Ana María Restrepo Vélez', CURRENT_TIMESTAMP),
    ('A00987654', 'Carlos Andrés Muñoz Salazar', CURRENT_TIMESTAMP);

INSERT INTO materia (codigo_materia, nombre, creditos) VALUES
    ('ING1234', 'Estructuras de Datos', 3),
    ('MAT2201', 'Cálculo Multivariado', 4),
    ('ING2345', 'Bases de Datos', 3);

INSERT INTO periodo_academico (codigo, fecha_inicio, fecha_fin, vigente) VALUES
    ('2026-1', DATE '2026-01-19', DATE '2026-05-23', FALSE),
    ('2026-2', DATE '2026-07-27', DATE '2026-11-28', TRUE);

-- Cuatro matrículas en el periodo vigente (2026-2).
-- nota_actual queda coherente con las evaluaciones que se insertan más abajo:
-- es el promedio ponderado normalizado por la suma de los porcentajes ya
-- registrados, igual que lo calcula EvaluacionSincronizacionService.
INSERT INTO matricula (codigo_estudiante, codigo_materia, periodo_academico, grupo, estado, nota_actual) VALUES
    -- Caso 1: con tres evaluaciones. (4.00*25 + 4.50*5 + 4.80*5) / 35 = 4.19
    ('A00123456', 'ING1234', '2026-2', '01', 'EN_CURSO', 4.19),
    -- Caso 2: sin ninguna evaluación todavía. Es la matrícula que usa la demo
    -- del endpoint de sincronización para ver nota_actual pasar de NULL a un valor.
    ('A00123456', 'MAT2201', '2026-2', '02', 'EN_CURSO', NULL),
    -- Caso 3: con una sola evaluación. (3.50*30) / 30 = 3.50
    ('A00123456', 'ING2345', '2026-2', '01', 'EN_CURSO', 3.50),
    -- Caso 4: segundo estudiante, para poder probar el 403 de un estudiante
    -- consultando los datos de otro. (4.00*10) / 10 = 4.00
    ('A00987654', 'ING1234', '2026-2', '02', 'EN_CURSO', 4.00);

-- Una matrícula del periodo histórico, ya cerrada, para ejercitar ?periodo=2026-1.
INSERT INTO matricula (codigo_estudiante, codigo_materia, periodo_academico, grupo, estado, nota_actual) VALUES
    ('A00123456', 'MAT2201', '2026-1', '03', 'APROBADA', 3.80);

INSERT INTO evaluacion (matricula_id, tipo, nombre, valor, porcentaje, fecha)
SELECT m.id, 'PARCIAL', 'Parcial 1', 4.00, 25.00, DATE '2026-08-14'
FROM matricula m
WHERE m.codigo_estudiante = 'A00123456' AND m.codigo_materia = 'ING1234' AND m.periodo_academico = '2026-2';

INSERT INTO evaluacion (matricula_id, tipo, nombre, valor, porcentaje, fecha)
SELECT m.id, 'QUIZ', 'Quiz 2 - Recursión', 4.50, 5.00, DATE '2026-08-21'
FROM matricula m
WHERE m.codigo_estudiante = 'A00123456' AND m.codigo_materia = 'ING1234' AND m.periodo_academico = '2026-2';

INSERT INTO evaluacion (matricula_id, tipo, nombre, valor, porcentaje, fecha)
SELECT m.id, 'TAREA', 'Taller de árboles binarios', 4.80, 5.00, DATE '2026-08-25'
FROM matricula m
WHERE m.codigo_estudiante = 'A00123456' AND m.codigo_materia = 'ING1234' AND m.periodo_academico = '2026-2';

INSERT INTO evaluacion (matricula_id, tipo, nombre, valor, porcentaje, fecha)
SELECT m.id, 'PARCIAL', 'Parcial 1', 3.50, 30.00, DATE '2026-08-18'
FROM matricula m
WHERE m.codigo_estudiante = 'A00123456' AND m.codigo_materia = 'ING2345' AND m.periodo_academico = '2026-2';

INSERT INTO evaluacion (matricula_id, tipo, nombre, valor, porcentaje, fecha)
SELECT m.id, 'QUIZ', 'Quiz 1 - Complejidad', 4.00, 10.00, DATE '2026-08-12'
FROM matricula m
WHERE m.codigo_estudiante = 'A00987654' AND m.codigo_materia = 'ING1234' AND m.periodo_academico = '2026-2';

INSERT INTO evaluacion (matricula_id, tipo, nombre, valor, porcentaje, fecha)
SELECT m.id, 'EXAMEN_FINAL', 'Examen final', 3.80, 100.00, DATE '2026-05-15'
FROM matricula m
WHERE m.codigo_estudiante = 'A00123456' AND m.codigo_materia = 'MAT2201' AND m.periodo_academico = '2026-1';
